import { getUsersData } from "@/lib/users";
import { User } from "@/types";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Users",
  // description: "Generated by create next app",
};

export default async function UserPage() {
  const usersData: User[] = await getUsersData();
  return (
    <section>
      <h2>
        {" "}
        <Link href="/"> Go Back Home</Link>
      </h2>
      <br />
      <ul>
        {usersData.map((user: User) => (
          <li key={user.id}>
            <Link href={`users/${user.id}`}> {user.name}</Link>
            <br />
          </li>
        ))}
      </ul>
    </section>
  );
}
